apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-deployment
spec:
  template:
    spec:
      containers:
      - name: backend-api
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
spec:
  template:
    spec:
      containers:
      - name: frontend-spa
        resources:
          requests:
            memory: "16Mi"
            cpu: "25m"
          limits:
            memory: "32Mi"
            cpu: "50m"

